-- Add migration script here
CREATE TABLE epoch_data (
  attestationscount INT  NOT NULL,
  attesterslashingscount INT NOT NULL,
  averagevalidatorbalance INT NOT NULL,
  blockscount INT NOT NULL,
  depositscount INT NOT NULL,
  eligibleether INT NOT NULL,
  epoch INT PRIMARY KEY NOT NULL,
  finalized INT NOT NULL,
  globalparticipationrate REAL NOT NULL,
  missedblocks INT NOT NULL,
  orphanedblocks INT NOT NULL,
  proposedblocks INT NOT NULL,
  proposerslashingscount INT NOT NULL,
  rewards_exported INT NOT NULL,
  scheduledblocks INT NOT NULL,
  totalvalidatorbalance INT NOT NULL,
  ts VARCHAR NOT NULL,
  validatorscount INT NOT NULL,
  voluntaryexitscount INT NOT NULL,
  votedether INT NOT NULL,
  withdrawalcount INT NOT NULL
);

CREATE TABLE slot_data (
  attestationscount INT NOT NULL,
  attesterslashingscount INT NOT NULL,
  blockroot VARCHAR NOT NULL,
  depositscount INT NOT NULL,
  epoch INT NOT NULL,
  eth1data_blockhash VARCHAR NOT NULL,
  eth1data_depositcount INT NOT NULL,
  eth1data_depositroot VARCHAR NOT NULL,
  exec_base_fee_per_gas INT,
  exec_block_hash VARCHAR,
  exec_block_number INT,
  exec_extra_data VARCHAR,
  exec_fee_recipient VARCHAR,
  exec_gas_limit INT,
  exec_gas_used INT,
  exec_logs_bloom VARCHAR,
  exec_parent_hash VARCHAR,
  exec_random VARCHAR,
  exec_receipts_root VARCHAR,
  exec_state_root VARCHAR,
  exec_timestamp INT,
  exec_transactions_count INT NOT NULL,
  graffiti VARCHAR NOT NULL,
  graffiti_text VARCHAR NOT NULL,
  parentroot VARCHAR NOT NULL,
  proposer INT NOT NULL,
  proposerslashingscount INT NOT NULL,
  randaoreveal VARCHAR NOT NULL,
  signature VARCHAR NOT NULL,
  slot INT PRIMARY KEY NOT NULL,
  stateroot VARCHAR NOT NULL,
  status VARCHAR NOT NULL,
  syncaggregate_bits VARCHAR,
  syncaggregate_participation REAL NOT NULL,
  syncaggregate_signature VARCHAR,
  voluntaryexitscount INT NOT NULL,
  withdrawalcount INT NOT NULL
);

